#pragma once

#include "NativeGameplayTags.h"

// 프로젝트 전역 네이티브 GameplayTag 선언 (기획서 GameplayTag 계층 기반)
namespace StudyTags
{
    // State.*
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Idle);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Moving);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dodging);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_HitReact);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_AirBorne);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Finisher);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

    // Ability.* (GA 식별 + 입력 라우팅)
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dodge);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_JustCounter);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_AirLauncher);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_AirCombo);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Finisher);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_LockOn);

    // Effect.*
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_HitStop);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Knockback);

    // Status.*
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Invincible);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_SuperArmor);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_CanFinish);

    // Event.* (AnimNotify / GA 간 통신)
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HitReact);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ComboWindowOpen);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Melee_Hit);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Launched);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Executed);

    // Input.* (Enhanced Input → GA 활성화 라우팅)
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Attack);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_AirAttack);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Launcher);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Finisher);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Dodge);

    // Data.* (GameplayEffect SetByCaller 매그니튜드 키)
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_LaunchZ);
}
