#pragma once

#include "NativeGameplayTags.h"

// 프로젝트 전역 네이티브 GameplayTag 선언 (기획서 GameplayTag 계층 기반)
namespace StudyTags
{
    // State.*
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Idle);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Moving);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dodging);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_HitReact);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_AirBorne);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Knockdown);   // 착지 후 넉다운(쓰러져 일어나는 중) — 타격 불가
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Finisher);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);

    // Ability.* (GA 식별 + 입력 라우팅)
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combo);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dodge);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_JustCounter);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_AirLauncher);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_AirCombo);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Finisher);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_LockOn);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_EnemyAttack);   // 적 AI 공격 GA
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Stagger);       // 패리당한 적 스태거 GA

    // Effect.*
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_HitStop);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Knockback);

    // Status.*
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Invincible);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_SuperArmor);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_CanFinish);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Parrying);     // 저스트카운터 패리 윈도우 활성 중
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Staggered);    // 패리당해 경직(처형 오프닝)

    // Event.* (AnimNotify / GA 간 통신)
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HitReact);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ComboWindowOpen);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Melee_Hit);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Melee_HitStart);  // 노티파이: 타격 윈도우 시작
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Melee_HitEnd);    // 노티파이: 타격 윈도우 끝
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Launched);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Slammed);   // 공중콤보 마무리: 적을 바닥으로 내려찍기
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Executed);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Parried);    // 패리 성공 → 패리한 쪽(플레이어)에 전송
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Staggered);  // 패리당함 → 공격자(적)에 전송(스태거)

    // Input.* (Enhanced Input → GA 활성화 라우팅)
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Attack);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_AirAttack);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Launcher);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Finisher);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Dodge);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Parry);   // 저스트카운터(패리) 입력

    // Data.* (GameplayEffect SetByCaller 매그니튜드 키)
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
    STUDYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_LaunchZ);
}
